-- ============================================================
-- SBTS Initial Migration — Raw SQL Additions
-- ============================================================
-- Run this AFTER `prisma migrate dev` generates the base migration.
-- These are constraints that Prisma schema cannot express natively.

-- Partial unique index: only one active version per route at a time.
-- This prevents two admins from concurrently activating different versions.
CREATE UNIQUE INDEX route_versions_active_unique
  ON route_versions(route_id)
  WHERE is_active = true;

-- Additional performance indexes not generated by Prisma
CREATE INDEX idx_routes_start_stop ON routes(start_stop_id);
CREATE INDEX idx_routes_end_stop ON routes(end_stop_id);
CREATE INDEX idx_stops_terminal ON stops(terminal_id);
CREATE INDEX idx_buses_terminal ON buses(terminal_id);
CREATE INDEX idx_schedules_route ON schedules(route_id);
CREATE INDEX idx_schedules_version ON schedules(version_id);
CREATE INDEX idx_trips_bus ON trips(bus_id);
CREATE INDEX idx_trips_driver ON trips(driver_id);
CREATE INDEX idx_trips_version ON trips(version_id);
CREATE INDEX idx_trips_schedule ON trips(schedule_id);
CREATE INDEX idx_trips_status ON trips(status);
CREATE INDEX idx_trips_scheduled_start ON trips(scheduled_start);
CREATE INDEX idx_incidents_status ON incidents(status);
CREATE INDEX idx_incidents_trip ON incidents(trip_id);
CREATE INDEX idx_key_handovers_status ON key_handovers(status);
