// src/features/driver/constants/trips.ts

import { UpcomingTrip } from '../types';

export const ROUTE = {
  start: "Bole",
  destination: "Piassa",
  distance: "12.5 km",
  stops: 5,
  estimatedTime: "25 mins",
};

export const UPCOMING_TRIPS: UpcomingTrip[] = [
  {
    id: 1,
    route: "Bole → Megenagna",
    date: "Jul 22",
    time: "10:30 AM",
    stops: 8,
    distance: "8.5 km",
    status: "Scheduled",
  },
  {
    id: 2,
    route: "Piassa → Bole",
    date: "Jul 22",
    time: "1:30 PM",
    stops: 5,
    distance: "12.5 km",
    status: "Scheduled",
  },
  {
    id: 3,
    route: "Megenagna → Kazanchis",
    date: "Jul 23",
    time: "9:00 AM",
    stops: 3,
    distance: "4.2 km",
    status: "Scheduled",
  },
  {
    id: 4,
    route: "Kazanchis → Bole",
    date: "Jul 23",
    time: "2:00 PM",
    stops: 6,
    distance: "7.8 km",
    status: "Scheduled",
  },
];

export const STATUS_CONFIG = {
  Completed: {
    color: "text-green-600 dark:text-green-400",
    bg: "bg-green-50 dark:bg-green-900/30",
    label: "Completed",
  },
  Delayed: {
    color: "text-yellow-600 dark:text-yellow-400",
    bg: "bg-yellow-50 dark:bg-yellow-900/30",
    label: "Delayed",
  },
  Cancelled: {
    color: "text-red-600 dark:text-red-400",
    bg: "bg-red-50 dark:bg-red-900/30",
    label: "Cancelled",
  },
  "In-progress": {
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-50 dark:bg-blue-900/30",
    label: "In-progress",
  },
};

// ================================================================
// SAMPLE_TRIPS - This is what useTripState.ts is importing
// ================================================================

export const SAMPLE_TRIPS = [
  {
    id: "1",
    tripId: "SB-0215-01",
    date: "2026-02-15",
    route: "Bole - Meskel Square",
    routeCode: "L1",
    time: "06:30 - 07:45",
    bus: "SB-102",
    status: "Completed",
    stops: 12,
    distance: "18.5km",
    duration: "75m",
    passengers: 38,
    rating: 4.8,
    onTime: "Early 3m",
    fuelUsed: "12.5L",
    traffic: "Light",
    scheduledDeparture: "06:30",
    actualDeparture: "06:28",
    scheduledArrival: "07:45",
    actualArrival: "07:42",
    notes: "Smooth trip, all stops on time. Good morning traffic.",
    city: "Addis Ababa",
    routeType: "City Express",
    startStop: "Bole Medhanealem",
    endStop: "Meskel Square",
  },
  {
    id: "2",
    tripId: "SB-0214-03",
    date: "2026-02-14",
    route: "Piassa - Mexico",
    routeCode: "L2",
    time: "14:00 - 15:00",
    bus: "SB-205",
    status: "Delayed",
    stops: 10,
    distance: "12km",
    duration: "60m",
    passengers: 25,
    rating: 3.5,
    onTime: "Late 10m",
    fuelUsed: "8.2L",
    traffic: "Heavy",
    scheduledDeparture: "14:00",
    actualDeparture: "14:10",
    scheduledArrival: "15:00",
    actualArrival: "15:10",
    notes: "Heavy traffic caused delay.",
    city: "Addis Ababa",
    routeType: "City Shuttle",
    startStop: "Piassa Square",
    endStop: "Mexico Square",
  },
  {
    id: "3",
    tripId: "SB-0115-07",
    date: "2026-01-15",
    route: "Akaki - Kality",
    routeCode: "L3",
    time: "07:00 - 08:15",
    bus: "SB-301",
    status: "Completed",
    stops: 8,
    distance: "22km",
    duration: "75m",
    passengers: 42,
    rating: 4.9,
    onTime: "On Time",
    fuelUsed: "15.0L",
    traffic: "Moderate",
    scheduledDeparture: "07:00",
    actualDeparture: "07:02",
    scheduledArrival: "08:15",
    actualArrival: "08:15",
    notes: "All stops on schedule.",
    city: "Addis Ababa",
    routeType: "City Express",
    startStop: "Akaki",
    endStop: "Kality",
  },
  {
    id: "4",
    tripId: "SB-0114-12",
    date: "2026-01-14",
    route: "CMC - Saris",
    routeCode: "L4",
    time: "16:30 - 17:45",
    bus: "SB-407",
    status: "Cancelled",
    stops: 14,
    distance: "16km",
    duration: "75m",
    passengers: 0,
    rating: 0,
    onTime: "N/A",
    fuelUsed: "0L",
    traffic: "Moderate",
    scheduledDeparture: "16:30",
    actualDeparture: "16:30",
    scheduledArrival: "17:45",
    actualArrival: "17:45",
    notes: "Trip cancelled due to mechanical issue.",
    city: "Addis Ababa",
    routeType: "City Shuttle",
    startStop: "CMC",
    endStop: "Saris",
  },
  {
    id: "5",
    tripId: "SB-0113-05",
    date: "2026-01-13",
    route: "Ayat - Hayat",
    routeCode: "L5",
    time: "08:00 - 09:00",
    bus: "SB-509",
    status: "Completed",
    stops: 9,
    distance: "14.5km",
    duration: "60m",
    passengers: 31,
    rating: 4.6,
    onTime: "On Time",
    fuelUsed: "9.8L",
    traffic: "Light",
    scheduledDeparture: "08:00",
    actualDeparture: "08:00",
    scheduledArrival: "09:00",
    actualArrival: "09:00",
    notes: "Perfect trip.",
    city: "Addis Ababa",
    routeType: "City Express",
    startStop: "Ayat",
    endStop: "Hayat",
  },
] as const;